let allMusic = [
  {
    name: "The Rush",
    artist: "AViVA & Mblue",
    img: "music-1",
    src: "1.mp3",
  },
  {
    name: "Like This",
    artist: "Airmow",
    img: "music-2",
    src: "2.mp3",
  },
  {
    name: "CELESTE (feat. LissA)",
    artist: "Airmow",
    img: "music-3",
    src: "3.mp3",
  },
  {
    name: "HALLUCINATION (feat. LissA)",
    artist: "Airmow",
    img: "music-4",
    src: "4.mp3",
  },
  {
    name: "FADE AWAY",
    artist: "Airmow x Frizzy The Streetz",
    img: "music-5",
    src: "5.mp3",
  },
  {
    name: "Raising Hell (feat. Sam Tinnesz & Que Parks)",
    artist: "Alaina Cross",
    img: "music-6",
    src: "6.mp3",
  },
  {
    name: "Dirty Little Secret",
    artist: "Alaina Cross, UNSECRET & GREYLEE",
    img: "music-7",
    src: "7.mp3",
  },
  {
    name: "Bulletproof (ft. Boy Nash)",
    artist: "Apollo On The Run",
    img: "music-8",
    src: "8.mp3",
  },
  {
    name: "Cherry (feat. BEANIE)",
    artist: "Apollo On The Run",
    img: "music-9",
    src: "9.mp3",
  },
  {
    name: "Mama (ft. Liv Cartier)",
    artist: "Apollo On The Run",
    img: "music-10",
    src: "10.mp3",
  },
  {
    name: "Medusa (ft. updog)",
    artist: "Apollo On The Run",
    img: "music-11",
    src: "11.mp3",
  },
  {
    name: "Pay For It (ft. TEYA)",
    artist: "Apollo On The Run",
    img: "music-12",
    src: "12.mp3",
  },
  {
    name: "Sugar (ft. Georgina Black)",
    artist: "Apollo On The Run",
    img: "music-13",
    src: "13.mp3",
  },
  {
    name: "Deal Breaker",
    artist: "Apollo On The Run, TRUU, Bentez",
    img: "music-14",
    src: "14.mp3",
  },
  {
    name: "Figure You Out",
    artist: "BB Cooper & Jake Daniels",
    img: "music-15",
    src: "15.mp3",
  },
  {
    name: "Born To Lose (with SØR)",
    artist: "BB Cooper & Kaphy",
    img: "music-16",
    src: "16.mp3",
  },
  {
    name: "Anything You Want",
    artist: "BB Cooper",
    img: "music-17",
    src: "17.mp3",
  },
  {
    name: "Blame",
    artist: "BB Cooper",
    img: "music-18",
    src: "18.mp3",
  },
  {
    name: "Cut Out",
    artist: "BB Cooper",
    img: "music-19",
    src: "19.mp3",
  },
  {
    name: "In My Dreams",
    artist: "BB Cooper",
    img: "music-20",
    src: "20.mp3",
  },
  {
    name: "Make Me Wanna",
    artist: "BB Cooper",
    img: "music-21",
    src: "21.mp3",
  },
  {
    name: "Pain",
    artist: "BB Cooper",
    img: "music-22",
    src: "22.mp3",
  },
  {
    name: "Pour Your Poison",
    artist: "BB Cooper",
    img: "music-23",
    src: "23.mp3",
  },
  {
    name: "Save Me",
    artist: "BB Cooper",
    img: "music-24",
    src: "24.mp3",
  },
  {
    name: "Should Have Known",
    artist: "BB Cooper",
    img: "music-25",
    src: "25.mp3",
  },
  {
    name: "WYTWM",
    artist: "BB Cooper",
    img: "music-26",
    src: "26.mp3",
  },
  {
    name: "Monster",
    artist: "BB Cooper, Jake Daniels, Kaphy",
    img: "music-27",
    src: "27.mp3",
  },
  {
    name: "Wine",
    artist: "BLVKES",
    img: "music-28",
    src: "28.mp3",
  },
  {
    name: "Love Me Anyway",
    artist: "Bentez & TRUU",
    img: "music-29",
    src: "29.mp3",
  },
  {
    name: "Ghost",
    artist: "Bentez",
    img: "music-30",
    src: "30.mp3",
  },
  {
    name: "Good Manners",
    artist: "Bentez",
    img: "music-31",
    src: "31.mp3",
  },
  {
    name: "I Dare You",
    artist: "Bentez",
    img: "music-32",
    src: "32.mp3",
  },
  {
    name: "Richest Man Alive",
    artist: "Bentez",
    img: "music-33",
    src: "33.mp3",
  },
  {
    name: "Therapy",
    artist: "Bentez",
    img: "music-34",
    src: "34.mp3",
  },
  {
    name: "Venom",
    artist: "Bentez",
    img: "music-35",
    src: "35.mp3",
  },
  {
    name: "I Don't Wanna Talk",
    artist: "Besomorph & HALUNA",
    img: "music-36",
    src: "36.mp3",
  },
  {
    name: "IDGAF",
    artist: "Besomorph & Silent Child",
    img: "music-37",
    src: "37.mp3",
  },
  {
    name: "Sweet Karma (feat. Adam Woods)",
    artist: "Besomorph",
    img: "music-38",
    src: "38.mp3",
  },
  {
    name: "Capsize",
    artist: "Biometrix",
    img: "music-39",
    src: "39.mp3",
  },
  {
    name: "Down Below",
    artist: "Biometrix",
    img: "music-40",
    src: "40.mp3",
  },
  {
    name: "The Upside Down (ft. Sarah de Warren)",
    artist: "Biometrix",
    img: "music-41",
    src: "41.mp3",
  },
  {
    name: "Dating Losers",
    artist: "Biometrix x Cheska Moore",
    img: "music-42",
    src: "42.mp3",
  },
  {
    name: "Ultraviolet",
    artist: "Biometrix x Hex & Solstice",
    img: "music-43",
    src: "43.mp3",
  },
  {
    name: "GOLD",
    artist: "Biometrix x LOU",
    img: "music-44",
    src: "44.mp3",
  },
  {
    name: "Begging",
    artist: "Blush Davis",
    img: "music-45",
    src: "45.mp3",
  },
  {
    name: "Lipstick on the Rearview",
    artist: "Blush Davis",
    img: "music-46",
    src: "46.mp3",
  },
  {
    name: "Point of View",
    artist: "Blush Davis",
    img: "music-47",
    src: "47.mp3",
  },
  {
    name: "The Beach",
    artist: "Blush Davis",
    img: "music-48",
    src: "48.mp3",
  },
  {
    name: "i love you don't worry xx",
    artist: "Blush Davis",
    img: "music-49",
    src: "49.mp3",
  },
  {
    name: "Nyx",
    artist: "Brad Arthur & Tokyo Project",
    img: "music-50",
    src: "50.mp3",
  },
  {
    name: "Believer",
    artist: "CLOWN",
    img: "music-51",
    src: "51.mp3",
  },
  {
    name: "Bang Bang",
    artist: "CRÈME & Silent Child",
    img: "music-52",
    src: "52.mp3",
  },
  {
    name: "Lost Souls (feat. sebabrazy)",
    artist: "Cadmium, Mblue, Cheska Moore",
    img: "music-53",
    src: "53.mp3",
  },
  {
    name: "Bad Thoughts",
    artist: "Cheska Moore",
    img: "music-54",
    src: "54.mp3",
  },
  {
    name: "Narcissist",
    artist: "Cheska Moore",
    img: "music-55",
    src: "55.mp3",
  },
  {
    name: "Nightmare",
    artist: "Cheska Moore",
    img: "music-56",
    src: "56.mp3",
  },
  {
    name: "Psychos In Love",
    artist: "Cheska Moore",
    img: "music-57",
    src: "57.mp3",
  },
  {
    name: "Trauma",
    artist: "Cheska Moore",
    img: "music-58",
    src: "58.mp3",
  },
  {
    name: "RUDE",
    artist: "Confetti & Saint Chaos",
    img: "music-59",
    src: "59.mp3",
  },
  {
    name: "Balloons",
    artist: "Confetti",
    img: "music-60",
    src: "60.mp3",
  },
  {
    name: "Ghost (Dark Version)",
    artist: "Confetti",
    img: "music-61",
    src: "61.mp3",
  },
  {
    name: "Ghost",
    artist: "Confetti",
    img: "music-62",
    src: "62.mp3",
  },
  {
    name: "Hot",
    artist: "Confetti",
    img: "music-63",
    src: "63.mp3",
  },
  {
    name: "Rob A Bank (The FifthGuys Remix)",
    artist: "Confetti",
    img: "music-64",
    src: "64.mp3",
  },
  {
    name: "Rob A Bank",
    artist: "Confetti",
    img: "music-65",
    src: "65.mp3",
  },
  {
    name: "Cradles",
    artist: "Unknown",
    img: "music-66",
    src: "66.mp3",
  },
  {
    name: "Do You Feel Good？",
    artist: "Crypto & BB Cooper",
    img: "music-67",
    src: "67.mp3",
  },
  {
    name: "Blue Tick",
    artist: "Crypto & Biometrix",
    img: "music-68",
    src: "68.mp3",
  },
  {
    name: "Sucker",
    artist: "Crypto & Cheska Moore",
    img: "music-69",
    src: "69.mp3",
  },
  {
    name: "Creep",
    artist: "Crypto & Christina O’Connor",
    img: "music-70",
    src: "70.mp3",
  },
  {
    name: "Song 2",
    artist: "Crypto & Confetti",
    img: "music-71",
    src: "71.mp3",
  },
  {
    name: "Daylight",
    artist: "Crypto & DEIIN",
    img: "music-72",
    src: "72.mp3",
  },
  {
    name: "Settle Down",
    artist: "Crypto & DEIIN",
    img: "music-73",
    src: "73.mp3",
  },
  {
    name: "Bringing Me Down",
    artist: "Crypto & Jake Daniels",
    img: "music-74",
    src: "74.mp3",
  },
  {
    name: "Hayloft",
    artist: "Crypto & Jake Daniels",
    img: "music-75",
    src: "75.mp3",
  },
  {
    name: "Love The Game (ft. Liza)",
    artist: "Crypto & Kaphy",
    img: "music-76",
    src: "76.mp3",
  },
  {
    name: "Game Over",
    artist: "Crypto & Mia Vaile",
    img: "music-77",
    src: "77.mp3",
  },
  {
    name: "Hit Me With Your Best Shot",
    artist: "Crypto & Opi",
    img: "music-78",
    src: "78.mp3",
  },
  {
    name: "Faded (feat. Constance)",
    artist: "Crypto",
    img: "music-79",
    src: "79.mp3",
  },
  {
    name: "Feel Good Inc. (feat. updog)",
    artist: "Crypto",
    img: "music-80",
    src: "80.mp3",
  },
  {
    name: "Love Me Again (feat. Guilty Empress)",
    artist: "Crypto",
    img: "music-81",
    src: "81.mp3",
  },
  {
    name: "Meant Something To You (feat. KnownasNat)",
    artist: "Crypto",
    img: "music-82",
    src: "82.mp3",
  },
  {
    name: "Faded (Dark Version)",
    artist: "Crypto feat. Constance",
    img: "music-83",
    src: "83.mp3",
  },
  {
    name: "Toxic",
    artist: "Crypto x Liza",
    img: "music-84",
    src: "84.mp3",
  },
  {
    name: "Nothing In My Pocket",
    artist: "DEIIN",
    img: "music-85",
    src: "85.mp3",
  },
  {
    name: "Open Your Eyes",
    artist: "DEIIN",
    img: "music-86",
    src: "86.mp3",
  },
  {
    name: "SPEED.",
    artist: "DEIIN",
    img: "music-87",
    src: "87.mp3",
  },
  {
    name: "everybodyeveryone",
    artist: "DEIIN",
    img: "music-88",
    src: "88.mp3",
  },
  {
    name: "it's hard!",
    artist: "DEIIN",
    img: "music-89",
    src: "89.mp3",
  },
  {
    name: "stay with u",
    artist: "DEIIN",
    img: "music-90",
    src: "90.mp3",
  },
  {
    name: "BLACKBLUEYELLOW",
    artist: "Diana Goldberg",
    img: "music-91",
    src: "91.mp3",
  },
  {
    name: "WHO NEEDS ENEMIES",
    artist: "Diana Goldberg",
    img: "music-92",
    src: "92.mp3",
  },
  {
    name: "ugh!",
    artist: "Dwilly",
    img: "music-93",
    src: "93.mp3",
  },
  {
    name: "Love Is War",
    artist: "ELIA EX",
    img: "music-94",
    src: "94.mp3",
  },
  {
    name: "NOT RIGHT",
    artist: "ELIA EX",
    img: "music-95",
    src: "95.mp3",
  },
  {
    name: "Burn In Hell",
    artist: "EMM",
    img: "music-96",
    src: "96.mp3",
  },
  {
    name: "Superfreak",
    artist: "EMM",
    img: "music-97",
    src: "97.mp3",
  },
  {
    name: "All I Need",
    artist: "Eros & DEIIN",
    img: "music-98",
    src: "98.mp3",
  },
  {
    name: "Locked Into Midnight",
    artist: "Eros",
    img: "music-99",
    src: "99.mp3",
  },
  {
    name: "Come After Dark",
    artist: "Eros x LEOWOLF",
    img: "music-100",
    src: "100.mp3",
  },
  {
    name: "Too Late To Love You",
    artist: "Ex Habit",
    img: "music-101",
    src: "101.mp3",
  },
  {
    name: "Who Do You Want",
    artist: "Ex Habit",
    img: "music-102",
    src: "102.mp3",
  },
  {
    name: "Kids See Ghosts",
    artist: "Frizzy The Streetz & Simbai",
    img: "music-103",
    src: "103.mp3",
  },
  {
    name: "Doll House",
    artist: "Georgina Black",
    img: "music-104",
    src: "104.mp3",
  },
  {
    name: "SCREAM",
    artist: "Georgina Black",
    img: "music-105",
    src: "105.mp3",
  },
  {
    name: "Feel Young",
    artist: "Highway Gloom",
    img: "music-106",
    src: "106.mp3",
  },
  {
    name: "High",
    artist: "Highway Gloom",
    img: "music-107",
    src: "107.mp3",
  },
  {
    name: "Nights Go On",
    artist: "Highway Gloom",
    img: "music-108",
    src: "108.mp3",
  },
  {
    name: "Rooms",
    artist: "Highway Gloom",
    img: "music-109",
    src: "109.mp3",
  },
  {
    name: "Saved You",
    artist: "IOVA",
    img: "music-110",
    src: "110.mp3",
  },
  {
    name: "DEAD INSIDE",
    artist: "In Waves",
    img: "music-111",
    src: "111.mp3",
  },
  {
    name: "HELLFIRE",
    artist: "In Waves",
    img: "music-112",
    src: "112.mp3",
  },
  {
    name: "Hands",
    artist: "In Waves",
    img: "music-113",
    src: "113.mp3",
  },
  {
    name: "MONSTERS",
    artist: "In Waves",
    img: "music-114",
    src: "114.mp3",
  },
  {
    name: "NIGHTMARES 🧟‍♂️",
    artist: "In Waves",
    img: "music-115",
    src: "115.mp3",
  },
  {
    name: "PURGE",
    artist: "In Waves",
    img: "music-116",
    src: "116.mp3",
  },
  {
    name: "Save Me",
    artist: "In Waves",
    img: "music-117",
    src: "117.mp3",
  },
  {
    name: "Skeletons",
    artist: "In Waves",
    img: "music-118",
    src: "118.mp3",
  },
  {
    name: "smiling through the pain",
    artist: "In Waves",
    img: "music-119",
    src: "119.mp3",
  },
  {
    name: "Freak Show (Lyric Video)",
    artist: "Jake Daniels & AViVA",
    img: "music-120",
    src: "120.mp3",
  },
  {
    name: "Mistakes",
    artist: "Jake Daniels & BB Cooper",
    img: "music-121",
    src: "121.mp3",
  },
  {
    name: "Basket Case",
    artist: "Jake Daniels & Bentez",
    img: "music-122",
    src: "122.mp3",
  },
  {
    name: "A Little Bit",
    artist: "Jake Daniels",
    img: "music-123",
    src: "123.mp3",
  },
  {
    name: "Bad Girl",
    artist: "Jake Daniels",
    img: "music-124",
    src: "124.mp3",
  },
  {
    name: "Bad Side",
    artist: "Jake Daniels",
    img: "music-125",
    src: "125.mp3",
  },
  {
    name: "Bad",
    artist: "Jake Daniels",
    img: "music-126",
    src: "126.mp3",
  },
  {
    name: "Crazy",
    artist: "Jake Daniels",
    img: "music-127",
    src: "127.mp3",
  },
  {
    name: "Djamila",
    artist: "Jake Daniels",
    img: "music-128",
    src: "128.mp3",
  },
  {
    name: "FCKED",
    artist: "Jake Daniels",
    img: "music-129",
    src: "129.mp3",
  },
  {
    name: "God",
    artist: "Jake Daniels",
    img: "music-130",
    src: "130.mp3",
  },
  {
    name: "Gone",
    artist: "Jake Daniels",
    img: "music-131",
    src: "131.mp3",
  },
  {
    name: "Jeepers Creepers",
    artist: "Jake Daniels",
    img: "music-132",
    src: "132.mp3",
  },
  {
    name: "Liar (Dark Version)",
    artist: "Jake Daniels",
    img: "music-133",
    src: "133.mp3",
  },
  {
    name: "Liar",
    artist: "Jake Daniels",
    img: "music-134",
    src: "134.mp3",
  },
  {
    name: "Pain",
    artist: "Jake Daniels",
    img: "music-135",
    src: "135.mp3",
  },
  {
    name: "Psycho",
    artist: "Jake Daniels",
    img: "music-136",
    src: "136.mp3",
  },
  {
    name: "Save Ya",
    artist: "Jake Daniels",
    img: "music-137",
    src: "137.mp3",
  },
  {
    name: "Scream (Lyric Video)",
    artist: "Jake Daniels",
    img: "music-138",
    src: "138.mp3",
  },
  {
    name: "Slave (for your love)",
    artist: "Jake Daniels",
    img: "music-139",
    src: "139.mp3",
  },
  {
    name: "Stalker",
    artist: "Jake Daniels",
    img: "music-140",
    src: "140.mp3",
  },
  {
    name: "Taste",
    artist: "Jake Daniels",
    img: "music-141",
    src: "141.mp3",
  },
  {
    name: "The Game",
    artist: "Jake Daniels",
    img: "music-142",
    src: "142.mp3",
  },
  {
    name: "The Otherside",
    artist: "Jake Daniels",
    img: "music-143",
    src: "143.mp3",
  },
  {
    name: "Two Face Dark Version (Lyric Video)",
    artist: "Jake Daniels",
    img: "music-144",
    src: "144.mp3",
  },
  {
    name: "Best Western",
    artist: "Joey Myron & Lucky Dog",
    img: "music-145",
    src: "145.mp3",
  },
  {
    name: "like i used to",
    artist: "Joseph Feinstein",
    img: "music-146",
    src: "146.mp3",
  },
  {
    name: "DARKNESS",
    artist: "Kaila Hoy",
    img: "music-147",
    src: "147.mp3",
  },
  {
    name: "Alive",
    artist: "Kaphy & DEIIN",
    img: "music-148",
    src: "148.mp3",
  },
  {
    name: "IN MY MIND",
    artist: "Kaphy & DEIIN",
    img: "music-149",
    src: "149.mp3",
  },
  {
    name: "Now You Know Me",
    artist: "Kaphy & DEIIN",
    img: "music-150",
    src: "150.mp3",
  },
  {
    name: "Won't Run Away",
    artist: "Kaphy & DEIIN",
    img: "music-151",
    src: "151.mp3",
  },
  {
    name: "Darkside",
    artist: "Kaphy & KONG.",
    img: "music-152",
    src: "152.mp3",
  },
  {
    name: "Burning Inside (ft. Barmuda)",
    artist: "Kaphy & Lone Me",
    img: "music-153",
    src: "153.mp3",
  },
  {
    name: "Meanwhile",
    artist: "Kaphy & SUNZZ",
    img: "music-154",
    src: "154.mp3",
  },
  {
    name: "deserved (feat. Barmuda)",
    artist: "Kaphy",
    img: "music-155",
    src: "155.mp3",
  },
  {
    name: "BRING ME DOWN",
    artist: "Khamsin",
    img: "music-156",
    src: "156.mp3",
  },
  {
    name: "TAKE IT LIKE A GIRL",
    artist: "Khamsin, Molly Moore & Win and Woo",
    img: "music-157",
    src: "157.mp3",
  },
  {
    name: "Inside a Lighter",
    artist: "Kiyashqo",
    img: "music-158",
    src: "158.mp3",
  },
  {
    name: "Cuz You're Beautiful",
    artist: "Kiyashqo",
    img: "music-159",
    src: "159.mp3",
  },
  {
    name: "Good Girl",
    artist: "Kiyashqo",
    img: "music-160",
    src: "160.mp3",
  },
  {
    name: "Bad Behaviour",
    artist: "LEOWOLF",
    img: "music-161",
    src: "161.mp3",
  },
  {
    name: "City Of God",
    artist: "LEOWOLF",
    img: "music-162",
    src: "162.mp3",
  },
  {
    name: "Criminal",
    artist: "LEOWOLF",
    img: "music-163",
    src: "163.mp3",
  },
  {
    name: "Haven't Found The Line",
    artist: "LEOWOLF",
    img: "music-164",
    src: "164.mp3",
  },
  {
    name: "Out Of The Blue",
    artist: "LEOWOLF",
    img: "music-165",
    src: "165.mp3",
  },
  {
    name: "Rock My World",
    artist: "LEOWOLF",
    img: "music-166",
    src: "166.mp3",
  },
  {
    name: "Romantic Gangster",
    artist: "LEOWOLF",
    img: "music-167",
    src: "167.mp3",
  },
  {
    name: "Time",
    artist: "LEOWOLF",
    img: "music-168",
    src: "168.mp3",
  },
  {
    name: "wasting time",
    artist: "Lani Daye",
    img: "music-169",
    src: "169.mp3",
  },
  {
    name: "ALPHA",
    artist: "Layto",
    img: "music-170",
    src: "170.mp3",
  },
  {
    name: "Ghost Town",
    artist: "Layto x Neoni",
    img: "music-171",
    src: "171.mp3",
  },
  {
    name: "Gold Digger",
    artist: "Lone Me, NotAVillain & ALYEN EYES",
    img: "music-172",
    src: "172.mp3",
  },
  {
    name: "Flash",
    artist: "MEMBA",
    img: "music-173",
    src: "173.mp3",
  },
  {
    name: "What Makes Us Alive",
    artist: "Mblue",
    img: "music-174",
    src: "174.mp3",
  },
  {
    name: "Closer To The Sun",
    artist: "Mblue",
    img: "music-175",
    src: "175.mp3",
  },
  {
    name: "Ecstasy",
    artist: "Mblue",
    img: "music-176",
    src: "176.mp3",
  },
  {
    name: "Lost",
    artist: "Mblue",
    img: "music-177",
    src: "177.mp3",
  },
  {
    name: "Try",
    artist: "Mblue",
    img: "music-178",
    src: "178.mp3",
  },
  {
    name: "Can't Tell Me Nothing",
    artist: "Mia Vaile",
    img: "music-179",
    src: "179.mp3",
  },
  {
    name: "Demon",
    artist: "Mia Vaile",
    img: "music-180",
    src: "180.mp3",
  },
  {
    name: "Chills (feat. Joey Myron)",
    artist: "Mickey Valen",
    img: "music-181",
    src: "181.mp3",
  },
  {
    name: "RIP (feat. Heather Jeanette)",
    artist: "Mickey Valen",
    img: "music-182",
    src: "182.mp3",
  },
  {
    name: "Undo Me",
    artist: "Mickey Valen, Emily Vaughn",
    img: "music-183",
    src: "183.mp3",
  },
  {
    name: "Fool",
    artist: "Mickey Valen, Felix Lean & Anna Cotter",
    img: "music-184",
    src: "184.mp3",
  },
  {
    name: "Chills (Dark Version)",
    artist: "Mickey Valen, Joey Myron",
    img: "music-185",
    src: "185.mp3",
  },
  {
    name: "Chills (Nashville Version)",
    artist: "Mickey Valen, Joey Myron, Lucky Dog",
    img: "music-186",
    src: "186.mp3",
  },
  {
    name: "M.E.A.N",
    artist: "NUVILICES",
    img: "music-187",
    src: "187.mp3",
  },
  {
    name: "moneyMONEY",
    artist: "NUVILICES",
    img: "music-188",
    src: "188.mp3",
  },
  {
    name: "paper tiger",
    artist: "NUVILICES",
    img: "music-189",
    src: "189.mp3",
  },
  {
    name: "DARKSIDE (Besomorph Remix)",
    artist: "Neoni",
    img: "music-190",
    src: "190.mp3",
  },
  {
    name: "DARKSIDE",
    artist: "Neoni",
    img: "music-191",
    src: "191.mp3",
  },
  {
    name: "LOSER",
    artist: "Neoni",
    img: "music-192",
    src: "192.mp3",
  },
  {
    name: "MUTINY",
    artist: "Neoni",
    img: "music-193",
    src: "193.mp3",
  },
  {
    name: "WONDERLAND",
    artist: "Neoni",
    img: "music-194",
    src: "194.mp3",
  },
  {
    name: "PLEASE",
    artist: "OMIDO & Ex Habit",
    img: "music-195",
    src: "195.mp3",
  },
  {
    name: "U in my head",
    artist: "OMIDO & TRUU",
    img: "music-196",
    src: "196.mp3",
  },
  {
    name: "Me & My Demons",
    artist: "OMIDO x Silent Child",
    img: "music-197",
    src: "197.mp3",
  },
  {
    name: "Toxic (ft. Rick Jansen)",
    artist: "Omido",
    img: "music-198",
    src: "198.mp3",
  },
  {
    name: "midas touch",
    artist: "One Hope & TRAILS",
    img: "music-199",
    src: "199.mp3",
  },
  {
    name: "wlfr",
    artist: "One Hope",
    img: "music-200",
    src: "200.mp3",
  },
  {
    name: "Situation Critical",
    artist: "POULISH KID",
    img: "music-201",
    src: "201.mp3",
  },
  {
    name: "CNTRL",
    artist: "Paper Idol",
    img: "music-202",
    src: "202.mp3",
  },
  {
    name: "Castles",
    artist: "Paper Idol",
    img: "music-203",
    src: "203.mp3",
  },
  {
    name: "Clouds",
    artist: "Paper Idol",
    img: "music-204",
    src: "204.mp3",
  },
  {
    name: "Dark Side Baby (PRNDL Remix)",
    artist: "Paper Idol",
    img: "music-205",
    src: "205.mp3",
  },
  {
    name: "James Bond",
    artist: "Paper Idol",
    img: "music-206",
    src: "206.mp3",
  },
  {
    name: "Sidewalk",
    artist: "Paper Idol",
    img: "music-207",
    src: "207.mp3",
  },
  {
    name: "The Playground (Crypto Remix)",
    artist: "Paper Idol",
    img: "music-208",
    src: "208.mp3",
  },
  {
    name: "What Happened To Us？",
    artist: "Paper Idol",
    img: "music-209",
    src: "209.mp3",
  },
  {
    name: "BLOOD",
    artist: "PatrickReza & Silent Child",
    img: "music-210",
    src: "210.mp3",
  },
  {
    name: "November",
    artist: "PatrickReza",
    img: "music-211",
    src: "211.mp3",
  },
  {
    name: "Badder Than The Bad Boys",
    artist: "Peyton Shay",
    img: "music-212",
    src: "212.mp3",
  },
  {
    name: "PowerTrip",
    artist: "Peyton Shay",
    img: "music-213",
    src: "213.mp3",
  },
  {
    name: "C＊caine Cowgirl",
    artist: "Pretty Sister",
    img: "music-214",
    src: "214.mp3",
  },
  {
    name: "Viva Las Vegas",
    artist: "Pretty Sister",
    img: "music-215",
    src: "215.mp3",
  },
  {
    name: "What's It Gonna Take？",
    artist: "Problem Solved & Lost Boy",
    img: "music-216",
    src: "216.mp3",
  },
  {
    name: "Crashing",
    artist: "QUINTA",
    img: "music-217",
    src: "217.mp3",
  },
  {
    name: "Drowning",
    artist: "QUINTA",
    img: "music-218",
    src: "218.mp3",
  },
  {
    name: "Touch Me",
    artist: "QUINTA",
    img: "music-219",
    src: "219.mp3",
  },
  {
    name: "Easy",
    artist: "R3YAN & CLRBLND.",
    img: "music-220",
    src: "220.mp3",
  },
  {
    name: "Monster (ft. YOTAL)",
    artist: "Roby Fayer",
    img: "music-221",
    src: "221.mp3",
  },
  {
    name: "P＊ssed Off",
    artist: "Roet & neverwaves",
    img: "music-222",
    src: "222.mp3",
  },
  {
    name: "I Might Be God",
    artist: "Say So City",
    img: "music-223",
    src: "223.mp3",
  },
  {
    name: "It's On",
    artist: "Say So City",
    img: "music-224",
    src: "224.mp3",
  },
  {
    name: "Your Danger",
    artist: "Say So City",
    img: "music-225",
    src: "225.mp3",
  },
  {
    name: "Class Clown",
    artist: "Silent Child & AViVA",
    img: "music-226",
    src: "226.mp3",
  },
  {
    name: "Jump (Lyric Video)",
    artist: "Silent Child & Patrick Reza",
    img: "music-227",
    src: "227.mp3",
  },
  {
    name: "Have My Back",
    artist: "Silent Child & Vanic",
    img: "music-228",
    src: "228.mp3",
  },
  {
    name: "Strange",
    artist: "Silent Child & margø",
    img: "music-229",
    src: "229.mp3",
  },
  {
    name: "ADHD",
    artist: "Silent Child",
    img: "music-230",
    src: "230.mp3",
  },
  {
    name: "F＊＊k You (Lyric Video)",
    artist: "Silent Child",
    img: "music-231",
    src: "231.mp3",
  },
  {
    name: "Happy",
    artist: "Silent Child",
    img: "music-232",
    src: "232.mp3",
  },
  {
    name: "IDFLU",
    artist: "Silent Child x DREAMERS",
    img: "music-233",
    src: "233.mp3",
  },
  {
    name: "Up In Flames feat. Emma Sameth (Lyric video)",
    artist: "Sinner's Heist",
    img: "music-234",
    src: "234.mp3",
  },
  {
    name: "Daredevil",
    artist: "Society of Villains",
    img: "music-235",
    src: "235.mp3",
  },
  {
    name: "Dirty Rotten Energy",
    artist: "Society of Villains",
    img: "music-236",
    src: "236.mp3",
  },
  {
    name: "Evil Is My Middle Name",
    artist: "Society of Villains",
    img: "music-237",
    src: "237.mp3",
  },
  {
    name: "Freaks",
    artist: "Society of Villains",
    img: "music-238",
    src: "238.mp3",
  },
  {
    name: "Good & Evil",
    artist: "Society of Villains",
    img: "music-239",
    src: "239.mp3",
  },
  {
    name: "Made a Monster",
    artist: "Society of Villains",
    img: "music-240",
    src: "240.mp3",
  },
  {
    name: "Smoke & Trouble",
    artist: "Society of Villains",
    img: "music-241",
    src: "241.mp3",
  },
  {
    name: "Sweeter Than Revenge",
    artist: "Society of Villains",
    img: "music-242",
    src: "242.mp3",
  },
  {
    name: "people pleaser",
    artist: "Solina",
    img: "music-243",
    src: "243.mp3",
  },
  {
    name: "Think Too Much",
    artist: "Stileto & Bryana Salaz",
    img: "music-244",
    src: "244.mp3",
  },
  {
    name: "Pretend",
    artist: "Stileto & Liza",
    img: "music-245",
    src: "245.mp3",
  },
  {
    name: "Immortal",
    artist: "Stileto & Silent Child",
    img: "music-246",
    src: "246.mp3",
  },
  {
    name: "Super Villain (feat. Kendyle Paige)",
    artist: "Stileto & Silent Child",
    img: "music-247",
    src: "247.mp3",
  },
  {
    name: "AI (feat. Geena Fontanella)",
    artist: "Stileto",
    img: "music-248",
    src: "248.mp3",
  },
  {
    name: "Cravin' (feat. Kendyle Paige)",
    artist: "Stileto",
    img: "music-249",
    src: "249.mp3",
  },
  {
    name: "Dead Or Alive (feat. Madalen Duke)",
    artist: "Stileto",
    img: "music-250",
    src: "250.mp3",
  },
  {
    name: "Erupt (ft. AViVA)",
    artist: "Stileto",
    img: "music-251",
    src: "251.mp3",
  },
  {
    name: "Joker",
    artist: "Stileto",
    img: "music-252",
    src: "252.mp3",
  },
  {
    name: "Skull n Bones",
    artist: "Stileto",
    img: "music-253",
    src: "253.mp3",
  },
  {
    name: "Demon Mode",
    artist: "Stileto, AViVA",
    img: "music-254",
    src: "254.mp3",
  },
  {
    name: "Summer Mix： 2025 ☀️",
    artist: "Unknown",
    img: "music-255",
    src: "255.mp3",
  },
  {
    name: "Immigrant Child",
    artist: "TEYA",
    img: "music-256",
    src: "256.mp3",
  },
  {
    name: "Not Scared of Growing Old",
    artist: "TEYA",
    img: "music-257",
    src: "257.mp3",
  },
  {
    name: "To-Do List",
    artist: "TEYA",
    img: "music-258",
    src: "258.mp3",
  },
  {
    name: "DEAD (SVDKO Remix)",
    artist: "TRAILS",
    img: "music-259",
    src: "259.mp3",
  },
  {
    name: "DEAD",
    artist: "TRAILS",
    img: "music-260",
    src: "260.mp3",
  },
  {
    name: "DISINTER MY HEART",
    artist: "TRAILS",
    img: "music-261",
    src: "261.mp3",
  },
  {
    name: "Enemy (Uptempo)",
    artist: "TRUU & Bentez",
    img: "music-262",
    src: "262.mp3",
  },
  {
    name: "Enemy",
    artist: "TRUU & Bentez",
    img: "music-263",
    src: "263.mp3",
  },
  {
    name: "Making Grown Men Cry (feat. TEYA)",
    artist: "TRUU",
    img: "music-264",
    src: "264.mp3",
  },
  {
    name: "Bittersweet",
    artist: "Tokyo Project & Brad Arthur",
    img: "music-265",
    src: "265.mp3",
  },
  {
    name: "Parasite",
    artist: "Tokyo Project & Diana Goldberg",
    img: "music-266",
    src: "266.mp3",
  },
  {
    name: "Resilience (feat. Bentez)",
    artist: "Tokyo Project & Mickey Valen",
    img: "music-267",
    src: "267.mp3",
  },
  {
    name: "Clouds",
    artist: "Tokyo Project & The People's Thieves",
    img: "music-268",
    src: "268.mp3",
  },
  {
    name: "155",
    artist: "Tokyo Project & Zaug",
    img: "music-269",
    src: "269.mp3",
  },
  {
    name: "Hide 'N Seek",
    artist: "Tokyo Project + Diana Goldberg",
    img: "music-270",
    src: "270.mp3",
  },
  {
    name: "Devil’s Ballet (ft. Silent Child & AViVA)",
    artist: "Tokyo Project",
    img: "music-271",
    src: "271.mp3",
  },
  {
    name: "My Perfection",
    artist: "Tokyo Project",
    img: "music-272",
    src: "272.mp3",
  },
  {
    name: "Chemical X (feat. TIMMS)",
    artist: "UNDREAM",
    img: "music-273",
    src: "273.mp3",
  },
  {
    name: "Fall Away (ft. Calivania)",
    artist: "UNDREAM",
    img: "music-274",
    src: "274.mp3",
  },
  {
    name: "Freak",
    artist: "UNDREAM",
    src: "275.mp3",
  },
  {
    name: "Nightmare (feat. Neoni)",
    artist: "UNDREAM",
    img: "music-276",
    src: "276.mp3",
  },
  {
    name: "Glow In The Dark",
    artist: "Unlike Pluto & Mike Taylor (UPxMT)",
    img: "music-277",
    src: "277.mp3",
  },
  {
    name: "Reckoning",
    artist: "Unlike Pluto & Mike Taylor (UPxMT)",
    img: "music-278",
    src: "278.mp3",
  },
  {
    name: "Villain",
    artist: "Unlike Pluto & Mike Taylor (UPxMT)",
    img: "music-279",
    src: "279.mp3",
  },
  {
    name: "If I Disappear",
    artist: "Unlike Pluto",
    img: "music-280",
    src: "280.mp3",
  },
  {
    name: "Is My Vision Scarred",
    artist: "Unlike Pluto",
    img: "music-281",
    src: "281.mp3",
  },
  {
    name: "Joke's On Me (feat. Joanna Jones)",
    artist: "Unlike Pluto",
    img: "music-282",
    src: "282.mp3",
  },
  {
    name: "Kiss Me To Sleep",
    artist: "Unlike Pluto",
    img: "music-283",
    src: "283.mp3",
  },
  {
    name: "Smile Like It Doesn't Sting",
    artist: "Unlike Pluto",
    img: "music-284",
    src: "284.mp3",
  },
  {
    name: "The In-Between",
    artist: "Unlike Pluto",
    img: "music-285",
    src: "285.mp3",
  },
  {
    name: "Thread",
    artist: "Unlike Pluto",
    img: "music-286",
    src: "286.mp3",
  },
  {
    name: "Glorious",
    artist: "Unroyal & Kendyle Paige",
    img: "music-287",
    src: "287.mp3",
  },
  {
    name: "BANG",
    artist: "Unroyal",
    img: "music-288",
    src: "288.mp3",
  },
  {
    name: "Monster",
    artist: "Unroyal",
    img: "music-289",
    src: "289.mp3",
  },
  {
    name: "Villain",
    artist: "Unroyal",
    img: "music-290",
    src: "290.mp3",
  },
  {
    name: "Naked",
    artist: "Vanic x Alexis Donn",
    img: "music-291",
    src: "291.mp3",
  },
  {
    name: "Close the Distance",
    artist: "Vanic x SYRE",
    img: "music-292",
    src: "292.mp3",
  },
  {
    name: "Villain Mode： Activated",
    artist: "Unknown",
    img: "music-293",
    src: "293.mp3",
  },
  {
    name: "Trenches (feat. Neoni)",
    artist: "Vosai",
    img: "music-294",
    src: "294.mp3",
  },
  {
    name: "OBSESSION",
    artist: "William Bolton",
    img: "music-295",
    src: "295.mp3",
  },
  {
    name: "RUNNING AWAY",
    artist: "William Bolton",
    img: "music-296",
    src: "296.mp3",
  },
  {
    name: "Sleeping Naked",
    artist: "XARMS",
    img: "music-297",
    src: "297.mp3",
  },
  {
    name: "Scream",
    artist: "Zaug",
    img: "music-298",
    src: "298.mp3",
  },
  {
    name: "Weeping Willow",
    artist: "Zaug",
    img: "music-299",
    src: "299.mp3",
  },
  {
    name: "NEW HOE",
    artist: "lyra lune",
    img: "music-300",
    src: "300.mp3",
  },
  {
    name: "someone else",
    artist: "margø",
    img: "music-301",
    src: "301.mp3",
  },
  {
    name: "Harley & Joker",
    artist: "notefly & BrillLion",
    img: "music-302",
    src: "302.mp3",
  },
  {
    name: "it always happens to me (ft. DEIIN)",
    artist: "notefly",
    img: "music-303",
    src: "303.mp3",
  },
  {
    name: "In A Grave",
    artist: "notefly, HVLO, IOVA",
    img: "music-304",
    src: "304.mp3",
  },
  {
    name: "CAN'T STOP NOW",
    artist: "problem solved & Civ Pierre",
    img: "music-305",
    src: "305.mp3",
  },
  {
    name: "IN ANOTHER LIFE",
    artist: "problem solved & Young Famous Ayz",
    img: "music-306",
    src: "306.mp3",
  },
  {
    name: "Wasting My Time",
    artist: "problem solved & Zee Will",
    img: "music-307",
    src: "307.mp3",
  },
  {
    name: "On The Throne",
    artist: "problem solved, Isabèl Usher & Zee Will",
    img: "music-308",
    src: "308.mp3",
  },
  {
    name: "DRIVIN' ME CRAZY",
    artist: "problem solved, JD Cliffe & Young Famous Ayz",
    img: "music-309",
    src: "309.mp3",
  },
  {
    name: "Need You (In My Life)",
    artist: "updog",
    img: "music-310",
    src: "310.mp3",
  },
  {
    name: "blah blah blah",
    artist: "updog",
    img: "music-311",
    src: "311.mp3",
  },
  {
    name: "cravin' you",
    artist: "updog",
    img: "music-312",
    src: "312.mp3",
  },
  {
    name: "endless nights",
    artist: "updog",
    img: "music-313",
    src: "313.mp3",
  },
  {
    name: "fade",
    artist: "updog",
    img: "music-314",
    src: "314.mp3",
  },
  {
    name: "get down",
    artist: "updog",
    img: "music-315",
    src: "315.mp3",
  },
  {
    name: "lovers ⧸ enemies",
    artist: "updog",
    img: "music-316",
    src: "316.mp3",
  },
  {
    name: "over my head",
    artist: "updog",
    img: "music-317",
    src: "317.mp3",
  },
  {
    name: "so you",
    artist: "updog",
    img: "music-318",
    src: "318.mp3",
  },
  {
    name: "spearhead",
    artist: "updog",
    img: "music-319",
    src: "319.mp3",
  },
  {
    name: "the other day",
    artist: "updog",
    img: "music-320",
    src: "320.mp3",
  },
  {
    name: "useless",
    artist: "updog",
    img: "music-321",
    src: "321.mp3",
  },
  {
    name: "what's updog",
    artist: "updog",
    img: "music-322",
    src: "322.mp3",
  },
  {
    name: "who am i to blame？",
    artist: "updog",
    img: "music-323",
    src: "323.mp3",
  },
  {
    name: "SuperVillain Origin Story",
    artist: "whatyoudid.",
    img: "music-324",
    src: "324.mp3",
  },
  {
    name: "What You Did",
    artist: "whatyoudid.",
    img: "music-325",
    src: "325.mp3",
  },
  {
    name: "Girls Just Want To Have Fun",
    artist: "why mona",
    img: "music-326",
    src: "326.mp3",
  }
];